version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:8.1-node
      - image: circleci/mysql:8.0.26
        environment:
          MYSQL_DB: demo_test
          MYSQL_USER: root
          MYSQL_PASSWORD: root
    environment:
      APP_ENV: test
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: demo_test
      DB_USERNAME: root
      DB_PASSWORD: root
    steps:
      - checkout
      - run: sudo composer self-update --1
      - run: composer install -n --prefer-dist --ignore-platform-req=ext-gd
      - run: npm ci
      - run: npm run dev
      - run:
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip
            -curl-sS https://getcomposer.org/installer | php
            -sudo mv composer.phar /usr/local/bin/composer
            libpq-dev
      - run:
          name: php test
          command: vendor/bin/phpunit
